packages:
  - "packages/*"

catalog:
  "@biomejs/biome": "^2.3.8"
  "@types/node": "^24.10.1"
  "@vitest/coverage-v8": "^4.0.12"
  pnpm: "^10.23.0"
  rimraf: "^6.1.2"
  rolldown: "^1.0.0-beta.53"
  tsx: "^4.0.0"
  turbo: "^2.0.0"
  typescript: "^5.6.0"
  vitest: "^4.0.12"
